server:
  port: 8080
spring:
  application:
    name: "reto-final"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:4w88feVkinwk5nRZ@cluster0.qvtv7tg.mongodb.net/?retryWrites=true&w=majority"
      database: "master"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
